name: Bundle BSX-Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependancies
        run: sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Get Pico SDK
        run: git clone --branch 1.5.1 --recurse-submodules https://github.com/raspberrypi/pico-sdk.git

      - name: Create Build Folder
        run: |
          mkdir build
    
      - name: Build Nova
        run: |
          cd ${{ github.workspace }}/build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DMODXO_PINOUT=nova .. 
          cmake --build .
      - name: Build Mini
          cd ${{ github.workspace}}/build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DMODXO_PINOUT=mini ..
          cmake --build .

      - name: List Files
        run: ls ${{ github.workspace }}/build

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          draft: true
          files: |
            ${{ github.workspace}}/build/bsx-nova.bin
            ${{ github.workspace}}/build/bsx-nova.uf2
            ${{ github.workspace}}/build/bsx-mini.bin
            ${{ github.workspace}}/build/bsx-mini.uf2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace}}/build/bsx-nova.bin
            ${{ github.workspace}}/build/bsx-nova.uf2
            ${{ github.workspace}}/build/bsx-mini.bin
            ${{ github.workspace}}/build/bsx-mini.uf2
